## PD 2.7.1
### Write a function that accepts two matrices and constructs their tensor product.

In [11]:
# Write a function that accepts two matrices and constructs their tensor product.
import numpy as np
def tensor_product(mat1, mat2):
    return np.kron(mat1, mat2)
# Example usage
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 5], [6, 7]])
result = tensor_product(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Tensor Product of A and B:\n", result)   

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[0 5]
 [6 7]]
Tensor Product of A and B:
 [[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]
